DISPLAY = '100'

# Used as sync init
SYNC_TWO_WAY = '200'
SYNC_SLOW = '201'
SYNC_ONE_WAY_FROM_CLIENT = '202'
SYNC_REFRESH_FROM_CLIENT = '203'
SYNC_ONE_WAY_FROM_SERVER = '204'
SYNC_REFRESH_FROM_SERVER = '205'

# Used by the server when alerting the sync
SYNC_TWO_WAY_BY_SERVER = '206'
SYNC_ONE_WAY_FROM_CLIENT_BY_SERVER = '207'
SYNC_REFRESH_FROM_CLIENT_BY_SERVER = '208'
SYNC_ONE_WAY_FROM_SERVER_BY_SERVER = '209'
SYNC_REFRESH_FROM_SERVER_BY_SERVER = '210'

SYNC_RESULT_ALERT = '221'
SYNC_NEXT_MESSAGE = '222'
SYNC_NO_END_OF_DATA = '223'

AUTHENTICATION_ACCEPTED = '212'
AUTHORIZATION_REQUIRED = '407'

SYNC_CAP_TWO_WAY = '1'
SYNC_CAP_SLOW_SYNC = '2'
SYNC_CAP_ONE_WAY_FROM_CLIENT = '3'
SYNC_CAP_REFRESH_FROM_CLIENT = '4'
SYNC_CAP_ONE_WAY_FROM_SERVER = '5'
SYNC_CAP_REFRESH_FROM_SERVER = '6'
SYNC_CAP_SERVER_ALERTED_SYNC = '7'

STATUS_OK = '200'
