language: python
python:
  - 2.6
  - 2.7
install:
    - pip install coveralls --use-wheel
    - pip install -e . --use-wheel
script:
    - coverage run --source=txsyncml `which trial` txsyncml
after_success:
    - coveralls
