language: python
env:
  - TXSYNCML_TEST_TIMEOUT=5
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libwbxml2-utils
install:
  - pip install coveralls --use-wheel
  - pip install -r requirements-dev.pip
  - pip install -e . --use-wheel
script:
  - coverage run --source=txsyncml `which trial` txsyncml
after_success:
  - coveralls
